name: validate-fhir-resources

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  validate-fhir-resource:
    name: validate fhir resources
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.2.42@sha256:99149098bc5e16f165dc0c742405ebe986498828ab372002d49a331b30256ee1
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure fhir cli
        run: |
          fhir config inflate All
          fhir config validator Advanced

      - name: Cache FHIR packages
        id: fhir-package-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            /github/home/.fhir/packages
            fhirpkg.lock.json
          key: fhir-packages-${{ hashFiles('package.json') }}
          restore-keys: |
            fhir-packages-

      - name: Restore FHIR package dependencies
        if: ${{ steps.fhir-package-cache.outputs.cache-hit != 'true' }}
        run: |
          fhir cache location --path
          fhir cache list
          fhir restore

      - name: Validate bundles
        continue-on-error: true
        run: |
          fhir cache location --path
          fhir cache list
          find lib/src/test/java/snapshots/ -type f \
            -name "*.fhir.json" -print0 | \
            xargs -0 -I {} sh -c 'echo "\n\n\nValidating: {}" && fhir validate --verbose --fail "{}"'
